config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  # get 'contacts/?page=' di
  devise_for :users
  root to: "contacts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  validates :lastname, presence: true
  before_validation :downcase_email

  accepts_nested_attributes_for :tags, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :taggings

  def name
    "#{lastname.upcase} #{firstname.capitalize} "
  end

  def downcase_email
    self.email.try(:downcase!)
  end

  def next
    Contact.where("id > ?", id).limit(1).first
  end

  def prev
    Contact.where("id < ?", id).last
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :contacts, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :contact

  accepts_nested_attributes_for :tag, :reject_if => :all_blank
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!

  def index
    if params[:tag]
      tags = Tag.where(name: params[:tag])
      @contacts = tags.map(&:contacts).flatten if tags.present? && tags.any?
    end
    params[:pagination] = params[:pagination].nil? ? 10 : params[:pagination].to_i
    params[:page] = "1" if params[:page].nil?
    @collection_size = !@contacts.nil? ? @contacts.count : Contact.count
    @number_of_pages = @collection_size.fdiv(params[:pagination]).ceil
    if @contacts.nil?
      @contacts = Contact.limit(params[:pagination])
      .offset((params[:page].to_i - 1) * params[:pagination])
    else
      @contacts = Contact.limit(params[:pagination])
      .offset((params[:page].to_i - 1) * params[:pagination]).where(id: @contacts.map(&:id))
    end

  end

  def new
    @contact = Contact.new
    @contact.tags.build
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to contact_path(@contact),
        notice: 'Contact was successfully created.'
    else

      render :new
    end

  end

  def edit
    @contact.tags.build if @contact.tags.empty?
  end

  def update
    if @contact.update(contact_params)
      redirect_to contact_path(@contact),
        notice: 'Contact was successfully updated.'
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @contact.destroy
    redirect_to contacts_path,
      notice: 'Contact was successfully destroyed.'
  end

  private

    def contact_params
      params.require(:contact).permit(
        :id, :firstname, :lastname, :email, :tel, :address, :tag_list,
        tags_attributes: [:id, :name, :_destroy]
        )
    end

    def set_contact
      @contact = Contact.find(params[:id])
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def safe_glyph glyph_name
    html = "<i class='glyphicon glyphicon-".html_safe
     html += glyph_name
     html += "'></i>".html_safe
  end

end

app/views/contacts/_form.html.erb
<%= simple_form_for @contact do |f| %>

  <div class="row">

    <div class="col-4">
      <%= f.input :firstname, label: "Prénom", class: "form-control form-control-sm" %>
    </div>

    <div class="col-4">
      <%= f.input :lastname, label: "Nom", class: "form-control form-control-sm" %>
    </div>

    <div class="col-4">
      <%= f.input :tel, label: "Tel", class: "form-control form-control-sm" %>
    </div>

    <div class="col-6">
      <%= f.input :email, label: "Email", class: "form-control form-control-sm" %>
    </div>

    <div class="col-6">
      <%= f.input :address, label: "Adresse", class: "form-control form-control-sm" %>
    </div>

  </div>

  <h3 style= 'color: grey;'>Ajouter des tags</h3>

  <div class="tags">
    <%= f.simple_fields_for :tags do |tag| %>
      <%= render 'contacts/tag_fields', f: tag %>
    <% end %>
  </div>

  <div class="col-12">

    <%= link_to_add_association button_tag((safe_glyph "plus"), type: "button", class: "close form-control btn"), f, :tags, 'data-association-insertion-node' => ".tags", 'data-association-insertion-method' => "append", style: ' display:inline; float:left;' %>
  </div>

  <%= f.submit class: "btn-info btn-lg btn-block" %>

<% end %>
<br>

<%= link_to ((safe_glyph "step-backward") + " Revenir à la liste de contacts"), contacts_path %>

app/views/contacts/_tag_fields.html.erb
<div class="nested-fields row">

  <div class="col-xs-10 ">
    <%= f.input :name, label: false, style: 'width:80%; display:inline; float:left;' %>
  </div>

  <div class="col-xs-2">
    <%= link_to_remove_association button_tag( (safe_glyph "remove-sign"),
    type: "button", class: "close form-control btn"), f, style: 'height:40%; width:20%; display:inline;' %>
  </div>

</div>

app/views/contacts/edit.html.erb
<h1> Editer Contact</h1>

<%= render 'form' %>

app/views/contacts/index.html.erb
<br>
<div class="row">
  <%= link_to ((safe_glyph "plus-sign") + " Nouveau contact"),
  new_contact_path(@contact), class:"ml-3 text-warning" %>&nbsp
  <%= link_to "Afficher 20 contacts par page", contacts_path +
   "?page="+ 1.to_s + "&pagination=" + 20.to_s + "&tag=" + params[:tag].to_s,
   class: "btn btn-info btn-sm" %> &nbsp
  <%= link_to "Afficher 50 contacts par page", contacts_path +
   "?page="+ 1.to_s + "&pagination=" + 50.to_s + "&tag=" + params[:tag].to_s,
   class: "btn btn-primary btn-sm" %>
</div>

<!--Table-->
<table class="table table-hover  table-striped table-sm">

  <!--Table head-->
  <thead>
    <tr class="table-info">
      <th class="align-middle"> <small> <%= safe_glyph "th-list" %></small> </th>
      <th class="align-middle" width="20%"><%= safe_glyph "user" %> Contact</th>
      <th class="align-middle" width="25%"> <%= safe_glyph "envelope" %> Email</th>
      <th class="align-middle" width="15%"> <%= safe_glyph "phone" %> Tel</th>
      <th class="align-middle"> <%= safe_glyph "tags" %> &nbsp Tags</th>
      <th class="align-middle"> </th>
      <th class="align-middle"> </th>
    </tr>
  </thead>
  <!--Table head end-->

  <!--Table body-->
  <tbody>

    <% @contacts.each do |contact | %>
      <tr>
        <td> <%= contact.id %></td>
        <td>
          <%= link_to contact.name, contact_path(contact) %>
        </td>
        <td> <%= contact.email %></td>
        <td> <%= contact.tel %></td>
        <td>

          <% contact.tags.each do |tag| %>
            <span class="badge badge-primary small">
              <%= link_to tag.name, contacts_path + "?page=" + 1.to_s + "&pagination=" +
              params[:pagination].to_s+ "&tag=" + tag.name.to_s, style: 'color: white;', class: 'small' %>
            </span>
          <% end %>

        </td>
        <td>
          <%= link_to (safe_glyph "pencil"), edit_contact_path(contact),
          class:"ml-3 text-warning" %>
        </td>
        <td>
          <%= link_to (safe_glyph "trash"), contact_path(contact),
            method: :delete, data: {confirm: "Confirmer la suppression ?"}, class:"ml-3 text-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <!--Table body end-->
</table>
<!--Table end-->

<!-- @pagination_size =  <%=  params[:pagination] %> <br>
@number_of_pages = <%=  @number_of_pages %> <br>
@collection_size =  <%=  @collection_size %> <br> -->

<!-- Current page = -->
<% current_page = params[:page] %>
<!-- previous page = -->
<%  previous_page = current_page.to_i > 1 ? (current_page.to_i - 1).to_s : "1" %>
<!-- next page =  -->
<%  next_page = current_page.to_i > 0 && current_page.to_i < @number_of_pages ?
 (current_page.to_i + 1).to_s : @number_of_pages.to_s %>

<ul class="pagination">
  <li class="page-item">
    <%= link_to "Precédent", contacts_path + "?page=" + previous_page +
    "&pagination=" + params[:pagination].to_s + "&tag=" + params[:tag].to_s, class: "page-link" %>
  </li>
  <%  1.upto(@number_of_pages) do |i| %>
    <% active = params[:page] == i.to_s ? "active" : ""  %>
    <li class="<%= active %>"> <%= link_to i, contacts_path + "?page=" + i.to_s +
    "&pagination=" + params[:pagination].to_s + "&tag=" + params[:tag].to_s %>
    </li>
  <% end %>
  <li class="page-item">
    <%= link_to "Suivant", contacts_path + "?page=" + next_page +
    "&pagination=" + params[:pagination].to_s + "&tag=" + params[:tag].to_s, class: "page-link " %>
  </li>
</ul>
<br>

app/views/contacts/new.html.erb
<h1>Nouveau Contact</h1>

<%= render 'form' %>

app/views/contacts/show.html.erb
<br>
<div class="flat-card">
  <div class="flat-card-content">
    <div class="flat-card-title">

      <div class=" text-center">
        <%= link_to (safe_glyph "chevron-left"),
          @contact.prev, style: "color: grey; font-size: 200%;" %> &nbsp
        <%= link_to (safe_glyph "chevron-right"),
          @contact.next, style: "color: grey; font-size: 200%;" %>

      </div>

      <h2 text-center>
         <%= safe_glyph "file" %> Contact
      </h2>

    </div>
      <p> <%= safe_glyph "user" %> <%= link_to @contact.name, contact_path(@contact) %></p>
      <p> <%= safe_glyph "envelope" %> <%= @contact.email %></p>
      <p> <%= safe_glyph "phone" %> <%= @contact.tel %></p>
      <p> <%= safe_glyph "map-marker" %> <%= @contact.address %></p>
      <div class="flex">
        <div class="flex">
          <%= safe_glyph "tags" %> &nbsp Tags &nbsp

            <% @contact.tags.each do |tag| %>
              <span class="badge badge-primary">
                <%= tag.name %>
              </span> &nbsp
            <% end %>
        </div>
      </div>
  </div>
  <div class="flat-card-actions">
    <%= link_to ((safe_glyph "pencil") + " Editer"), edit_contact_path(@contact), class:"ml-3 text-warning" %>
    <%= link_to ((safe_glyph "trash") + " Supprimer"), contact_path(@contact),
        method: :delete, data: {confirm: "Confirmer la suppression ?"}, class:"ml-3 text-danger" %>
    <%= link_to ((safe_glyph "step-backward") + " Revenir à la liste de contacts"), contacts_path %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <% stylesheet_pack_tag 'application', media: 'all' %>
    <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

</div>